rest: gunicorn -c gunicorn_config.py wsgi
wamp: python3 -u ws.py
work: celery -A worker worker -X "${SUPERDESK_CELERY_PREFIX}expiry,${SUPERDESK_CELERY_PREFIX}publish,${SUPERDESK_CELERY_PREFIX}publish_priority,${SUPERDESK_CELERY_PREFIX}ingest" --concurrency ${CELERY_WORKER_CONCURRENCY:-2}
beat: celery -A worker beat -S redbeat.RedBeatScheduler --max-interval 10